name: Open Pull Request

on:
  push:
    branchs:
      - feat/**

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Reset branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'feat: creating pull request'
          title: 'Auto opened PR - ${{ steps.cpr.outputs.pull-request-number }}'
          delete-branch: true
